package librarymanagementsystem;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;    
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import javax.swing.JTable;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


/**
 *
 * @author Daeniel Presa
 */
public class BorrowBooks extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    private int selectedBookID = -1;
    private String selectedBookName = null;
    private int selectedAvailableCopies = 0;
    
    public BorrowBooks() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a");
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt)))
        .start();
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt));
        loadBooks();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        dateandtimeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBorrow = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library Management System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnBorrow.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnBorrow.setText("Borrow Book");
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 170, 40));

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 530, 200));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTableMouseClicked
        int row = BookTable.getSelectedRow();
        if (row >= 0) {
        selectedBookID = Integer.parseInt(BookTable.getValueAt(row, 0).toString());
        selectedBookName = BookTable.getValueAt(row, 1).toString();
        selectedAvailableCopies = Integer.parseInt(BookTable.getValueAt(row, 2).toString());
        }
    }//GEN-LAST:event_BookTableMouseClicked

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        if (selectedBookName == null || SessionManager.userName == null) {
            JOptionPane.showMessageDialog(this, "Please select a book to borrow.");
            return;
        }

        String bookName = selectedBookName;
        String studentName = SessionManager.userName;

        String today = java.time.LocalDate.now().toString();
        String dueDate = java.time.LocalDate.now().plusDays(7).toString();

        if (canBorrow(studentName)) {
            borrowBook(bookName, studentName, today, dueDate);
        } else {
            JOptionPane.showMessageDialog(this, "This student has already borrowed 3 books. They cannot borrow more.");
        }
    }//GEN-LAST:event_btnBorrowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        UserHomePage UHPForm = new UserHomePage();
        UHPForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void borrowBook(String bookName, String studentName, String dateBorrowed, String dueDate) {
        String insertQuery = "INSERT INTO BorrowedBooks (BookName, StudentName, DateBorrowed, DueDate) VALUES (?, ?, ?, ?)";
        String updateQuery = "UPDATE BookInventory SET AvailableCopies = AvailableCopies - 1, BorrowedCopies = BorrowedCopies + 1 WHERE BookName = ? AND AvailableCopies > 0";

        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/lbs", "root", "MySQLPW_1234");
            PreparedStatement insertStmt = connection.prepareStatement(insertQuery);
            PreparedStatement updateStmt = connection.prepareStatement(updateQuery)) {

            insertStmt.setString(1, bookName);
            insertStmt.setString(2, studentName);
            insertStmt.setString(3, dateBorrowed);
            insertStmt.setString(4, dueDate);
            int rowsInserted = insertStmt.executeUpdate();

        if (rowsInserted > 0) {
            updateStmt.setString(1, bookName);
            int rowsAffected = updateStmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Book successfully borrowed and inventory updated!");
            } else {
                JOptionPane.showMessageDialog(this, "Error: No available copies of this book.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "An error occurred while borrowing the book.");
        }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }
    private boolean canBorrow(String studentName) {
        String query = "SELECT COUNT(*) FROM BorrowedBooks WHERE StudentName = ?";
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/lbs", "root", "MySQLPW_1234");
            PreparedStatement stmt = connection.prepareStatement(query)) {
            stmt.setString(1, studentName);
            ResultSet rs = stmt.executeQuery();
        if (rs.next()) {
            int count = rs.getInt(1);
            return count < 3;
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowBooks().setVisible(true);
            }
        });
    }
    
    private void loadBooks() {
    try {
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/lbs",
                "root",
                "MySQLPW_1234"
        );

        String sql = "SELECT * FROM BookInventory";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addColumn("BookID");
        model.addColumn("BookName");
        model.addColumn("Author");
        model.addColumn("YearPurchased");
        model.addColumn("AvailableCopies");

        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getInt("BookID"),
                    rs.getString("BookName"),
                    rs.getString("Author"),
                    rs.getInt("YearPurchased"),
                    rs.getInt("AvailableCopies")
            });
        }
        
        BookTable.setDefaultEditor(Object.class, null);

        BookTable.setAutoResizeMode(BookTable.AUTO_RESIZE_OFF);
        for (int col = 0; col < BookTable.getColumnCount(); col++) {
            int width = 50;
            for (int row = 0; row < BookTable.getRowCount(); row++) {
                TableCellRenderer renderer = BookTable.getCellRenderer(row, col);
                Component comp = BookTable.prepareRenderer(renderer, row, col);
                width = Math.max(comp.getPreferredSize().width + 10, width);
            }
            BookTable.getColumnModel().getColumn(col).setPreferredWidth(width);
        }

        BookTable.setModel(model);
        BookTable.setAutoResizeMode(BookTable.AUTO_RESIZE_ALL_COLUMNS);
        BookTable.setDefaultEditor(Object.class, null);


    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookTable;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
