/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;    
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.sql.ResultSet;

/**
 *
 * @author Daeniel Presa
 */
public class GenerateReport extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public GenerateReport() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a");
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt)))
        .start();
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt));
        setLocationRelativeTo(null);
        loadDisposeBooks();
        loadOverdueBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        dateandtimeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        ReturnOverdueTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookForDisposalTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Books due for disposal: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library Management System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Books currently overdue for return:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jPanel2.add(jScrollPane3);

        ReturnOverdueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(ReturnOverdueTable);

        jPanel2.add(jScrollPane4);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 450, 150));

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        BookForDisposalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BookForDisposalTable);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 450, 110));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        EmployeeHomePage EHPForm = new EmployeeHomePage();
        EHPForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void loadOverdueBooks(){
        try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234")) {

        String sql = "SELECT * FROM BorrowedBooks WHERE NOW() > DueDate";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addColumn("BorrowID");
        model.addColumn("BookName");
        model.addColumn("StudentName");
        model.addColumn("DateBorrowed");
        model.addColumn("DueDate");

        int rowCount = 0;
        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getInt("BorrowID"),
                    rs.getString("BookName"),
                    rs.getString("StudentName"),
                    rs.getTimestamp("DateBorrowed"),
                    rs.getTimestamp("DueDate")
            });
            rowCount++;
        }

        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null,
                    "No overdue books at the moment.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        ReturnOverdueTable.setModel(model);
        ReturnOverdueTable.setAutoResizeMode(ReturnOverdueTable.AUTO_RESIZE_OFF);

        // Only adjust column widths if we have rows
        if (rowCount > 0) {
            for (int col = 0; col < ReturnOverdueTable.getColumnCount(); col++) {
                int maxWidth = 50;
                for (int row = 0; row < ReturnOverdueTable.getRowCount(); row++) {
                    TableCellRenderer renderer = ReturnOverdueTable.getCellRenderer(row, col);
                    Component comp = ReturnOverdueTable.prepareRenderer(renderer, row, col);
                    maxWidth = Math.max(comp.getPreferredSize().width + 10, maxWidth);
                }

                TableCellRenderer headerRenderer = ReturnOverdueTable.getTableHeader().getDefaultRenderer();
                Component headerComp = headerRenderer.getTableCellRendererComponent(
                        ReturnOverdueTable,
                        ReturnOverdueTable.getColumnName(col),
                        false, false, 0, col
                );
                maxWidth = Math.max(maxWidth, headerComp.getPreferredSize().width + 10);

                ReturnOverdueTable.getColumnModel().getColumn(col).setPreferredWidth(maxWidth);
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }
    private void loadDisposeBooks() {
        try (Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/lbs",
        "root",
        "MySQLPW_1234")) {

        String sql = "SELECT * FROM BookInventory WHERE YearPurchased <= YEAR(CURDATE()) - 5";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0; // BookID not editable
            }
        };

        model.addColumn("BookID");
        model.addColumn("BookName");
        model.addColumn("Author");
        model.addColumn("YearPurchased");
        model.addColumn("AvailableCopies");

        int rowCount = 0;
        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getInt("BookID"),
                    rs.getString("BookName"),
                    rs.getString("Author"),
                    rs.getInt("YearPurchased"),
                    rs.getInt("AvailableCopies")
            });
            rowCount++;
        }

        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null,
                    "No books eligible for disposal.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        BookForDisposalTable.setModel(model);
        BookForDisposalTable.setAutoResizeMode(BookForDisposalTable.AUTO_RESIZE_OFF);

        if (rowCount > 0) {
            for (int col = 0; col < BookForDisposalTable.getColumnCount(); col++) {
                int maxWidth = 50;

                for (int row = 0; row < BookForDisposalTable.getRowCount(); row++) {
                    TableCellRenderer renderer = BookForDisposalTable.getCellRenderer(row, col);
                    Component comp = BookForDisposalTable.prepareRenderer(renderer, row, col);
                    maxWidth = Math.max(comp.getPreferredSize().width + 10, maxWidth);
                }

                TableCellRenderer headerRenderer = BookForDisposalTable.getTableHeader().getDefaultRenderer();
                Component headerComp = headerRenderer.getTableCellRendererComponent(
                        BookForDisposalTable,
                        BookForDisposalTable.getColumnName(col),
                        false, false, 0, col
                );
                maxWidth = Math.max(maxWidth, headerComp.getPreferredSize().width + 10);

                BookForDisposalTable.getColumnModel().getColumn(col).setPreferredWidth(maxWidth);
            }
        }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(
                        null,
                        "Database error: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookForDisposalTable;
    private javax.swing.JTable ReturnOverdueTable;
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
