/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author Daeniel Presa
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a"); // fetches date and time format, placed into fmt 
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt))).start(); // sets timer for every 60 seconds, it updates the label
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt)); // sets the time when program is run
        setLocationRelativeTo(null); // centers the form
        signupLabel.setText("<html><u>" + signupLabel.getText() + "</u></html>"); // makes the label have an underline
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        dateandtimeLabel = new javax.swing.JLabel();
        signupLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 20));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Library Management System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Log In");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 220, -1));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student/Employee ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 220, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("ENTER");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 110, -1));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        signupLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        signupLabel.setForeground(new java.awt.Color(204, 255, 255));
        signupLabel.setText("Don't have an account? Click here");
        signupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabelMouseClicked(evt);
            }
        });
        getContentPane().add(signupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, 20));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/logo.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseClicked
        this.dispose(); // removes current form
        UserSignupForm USUForm = new UserSignupForm(); // sets USUForm variable to store the specified form for redirection
        USUForm.setVisible(true); // makes form visible
    }//GEN-LAST:event_signupLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String id = txtID.getText().trim(); // fetches user input in text field
    String password = new String(txtPassword.getPassword()); // fetches user input in password field

    if (id.isEmpty() || password.isEmpty()) { //if either fields are empty, sends an error message
        JOptionPane.showMessageDialog(
                this,
                "Please enter ID and Password",
                "Missing Input",
                JOptionPane.ERROR_MESSAGE
        );
        return; // stop processing and exit the method

    }

    String url = "jdbc:mysql://localhost:3306/lbs"; // stores database url
    String user = "root"; // stores database password
    String pass = "MySQLPW_1234"; // stores database password

    try (Connection conn = DriverManager.getConnection(url, user, pass)) { // opens db connection
        
        // whole sql prompt to verify user info
        String studentSQL =
                "SELECT StudentID, StudentName FROM Students WHERE StudentID = ? AND Password = ?";

        try (PreparedStatement pst = conn.prepareStatement(studentSQL)) {
            pst.setString(1, id); // Sets the StudentID as first parameter
            pst.setString(2, password); // Sets the Password as second parameter
 
            try (ResultSet rs = pst.executeQuery()) { // executes query, stores results
                if (rs.next()) { //if user exists
                    SessionManager.userID = rs.getString("StudentID"); // stores user's ID
                    SessionManager.userName = rs.getString("StudentName"); //stores user's name
                    
                    // show successful login message dialog
                    JOptionPane.showMessageDialog(this, "Welcome, " + SessionManager.userName + "!");
                    // redirection block
                    this.dispose(); // removes current form
                    UserHomePage UHPForm = new UserHomePage(); // sets UHPForm variable to store the specified form for redirection
                    UHPForm.setVisible(true); // makes form Visible
                    return;
                }
            }
        }
        
        // whole sql prompt to verify user info
        String employeeSQL =
                "SELECT EmployeeID, EmployeeName FROM Employees WHERE EmployeeID = ? AND Password = ?";

        try (PreparedStatement pst = conn.prepareStatement(employeeSQL)) {
            pst.setString(1, id); // Sets the StudentID as first parameter
            pst.setString(2, password); // Sets the Password as second parameter

            try (ResultSet rs = pst.executeQuery()) { // executes query, stores results
                if (rs.next()) { // if employee exists
                    SessionManager.userID = rs.getString("EmployeeID"); // stores user's ID
                    SessionManager.userName = rs.getString("EmployeeName"); // stores user's name
                    // show successful message dialog 
                    JOptionPane.showMessageDialog(this, "Welcome, " + SessionManager.userName + "!");
                    this.dispose(); // removes current form 
                    EmployeeHomePage EHPForm = new EmployeeHomePage(); // sets EHPForm variable to store the specified form for redirection
                    EHPForm.setVisible(true); // makes form visible
                    return;
                }
            }
        }
        
        // if both are tried without matches, show message dialog
        JOptionPane.showMessageDialog(this,
                "Invalid ID or Password",
                "Login Failed",
                JOptionPane.ERROR_MESSAGE
        );
    
// if database error occurs, show message dialog
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(
                this,
                "Database error: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
