package librarymanagementsystem;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;    
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


/**
 *
 * @author Daeniel Presa
 */
public class ReturnBooks extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    // variables used for selection
    private int selectedBorrowID = -1;
    private Date selectedDateBorrowed = null;
    private Date selectedDueDate = null;

    public ReturnBooks() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a"); // fetches date and time format, placed into fmt 
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt))).start(); // sets timer for every 60 seconds, it updates the label
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt)); // sets current time and date with format to label
        loadMyBooks(); // calls table loading method
        setLocationRelativeTo(null); // sets form's location to center
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        dateandtimeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MyBooksTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library Management System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnReturn.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnReturn.setText("Return Book");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 170, 40));

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jPanel2.setBackground(new java.awt.Color(87, 87, 87));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MyBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MyBooksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyBooksTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MyBooksTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 530, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        if (selectedBorrowID == -1 || selectedDueDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a borrowed book first.");
            return;
        }

        Date today = new Date();
        long diffMillis = today.getTime() - selectedDueDate.getTime();
        long daysOverdue = TimeUnit.MILLISECONDS.toDays(diffMillis);
        // default penalty amount
        double fine = 0;
        if (daysOverdue > 0) {
            fine = daysOverdue * 50.0;
        }

        String message = "Return this book?";
        if (fine > 0) {
            message += "\nOverdue by " + daysOverdue + " day(s)\nFine: ₱" + fine;
        }

        int confirm = JOptionPane.showConfirmDialog(this, message, "Confirm Return", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        String insertHistory = "INSERT INTO TransactionHistory (StudentID, BookName, DateBorrowed, DueDate, ReturnDate, Penalty) VALUES (?, ?, ?, ?, ?, ?)";
        String deleteBorrowed = "DELETE FROM BorrowedBooks WHERE BorrowID = ?";
        String updateInventory = "UPDATE BookInventory SET AvailableCopies = AvailableCopies + 1, BorrowedCopies = BorrowedCopies - 1 WHERE BookName = ?";

        try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234");
            PreparedStatement insertStmt = conn.prepareStatement(insertHistory);
            PreparedStatement deleteStmt = conn.prepareStatement(deleteBorrowed);
            PreparedStatement updateStmt = conn.prepareStatement(updateInventory)) {

            String bookName = MyBooksTable.getValueAt(MyBooksTable.getSelectedRow(), 1).toString();
            Date dateBorrowed = (Date) MyBooksTable.getValueAt(MyBooksTable.getSelectedRow(), 3);

            insertStmt.setString(1, SessionManager.userID);
            insertStmt.setString(2, bookName);
            insertStmt.setDate(3, new java.sql.Date(dateBorrowed.getTime()));
            insertStmt.setDate(4, new java.sql.Date(selectedDueDate.getTime()));
            insertStmt.setDate(5, new java.sql.Date(today.getTime()));
            insertStmt.setDouble(6, fine);
            insertStmt.executeUpdate();

            deleteStmt.setInt(1, selectedBorrowID);
            deleteStmt.executeUpdate();

            updateStmt.setString(1, bookName);
            updateStmt.executeUpdate();

            if (fine > 0) {
                JOptionPane.showMessageDialog(this, "Book returned successfully.\nFine to pay: ₱" + fine);
            } else {
                JOptionPane.showMessageDialog(this, "Book returned successfully.");
            }

            selectedBorrowID = -1;
            selectedDateBorrowed = null;
            selectedDueDate = null;

            loadMyBooks();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); //
        UserHomePage UHPForm = new UserHomePage();
        UHPForm.setVisible(true); //
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MyBooksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyBooksTableMouseClicked
        // when table is clicked, it selects that row and fetches data and assigns it to the respective variables 
        int row = MyBooksTable.getSelectedRow();
        if (row >= 0) {
        selectedBorrowID = (int) MyBooksTable.getValueAt(row, 0);
        selectedDateBorrowed = (Date) MyBooksTable.getValueAt(row, 3);
        selectedDueDate = (Date) MyBooksTable.getValueAt(row, 4);
        }
    }//GEN-LAST:event_MyBooksTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBooks().setVisible(true);
            }
        });
    }
    
    // table loading method 
    private void loadMyBooks() {
    // connects to database
    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234")) {
        
        // SQL query for fetching records in database
        String sql = "SELECT * FROM BorrowedBooks WHERE StudentName = ? ORDER BY DateBorrowed DESC";
        PreparedStatement pst = con.prepareStatement(sql); // stores sql query to prepared statement
        pst.setString(1, SessionManager.userName); // sets currently logged on user as the first parameter

        ResultSet rs = pst.executeQuery(); // execute query

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // makes table uneditable
            }
        };
        
        // defines all columns to be displayed
        model.addColumn("BookID");
        model.addColumn("BookName");
        model.addColumn("StudentName");
        model.addColumn("DateBorrowed");
        model.addColumn("DueDate");
        
        // loops through each row and adds to the table
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("BorrowID"),
                rs.getString("BookName"),
                rs.getString("StudentName"),
                rs.getDate("DateBorrowed"),
                rs.getDate("DueDate")
            });
        }
        // sets model to existing table
        MyBooksTable.setModel(model);
        
        // adjust column width based on size
        for (int col = 0; col < MyBooksTable.getColumnCount(); col++) {
            int width = 50;
            // check width of each cell
            for (int row = 0; row < MyBooksTable.getRowCount(); row++) {
                TableCellRenderer renderer = MyBooksTable.getCellRenderer(row, col);
                Component comp = MyBooksTable.prepareRenderer(renderer, row, col);
                width = Math.max(comp.getPreferredSize().width + 10, width);
                }
                // adjust columm width based on header size
                TableCellRenderer headerRenderer = MyBooksTable.getTableHeader().getDefaultRenderer();
                    Component headerComp = headerRenderer.getTableCellRendererComponent(
                            MyBooksTable, 
                            MyBooksTable.getColumnName(col),
                            false, false, 0, col
                    );
                    width = Math.max(width,headerComp.getPreferredSize().width + 10);
                    MyBooksTable.getColumnModel().getColumn(col).setPreferredWidth(width);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Database error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MyBooksTable;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
