/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;
/**
 *
 * @author Daeniel Presa
 */
public class UserHomePage extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public UserHomePage() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a"); // fetches date and time with format, placed into fmt 
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt))).start(); // starts timer, every 60k ms = 1 minute, every minute it activates it fetches data and sets it to the label
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt)); // sets the date and time to label before update
        setLocationRelativeTo(null); // sets form location to center
        SwingUtilities.invokeLater(() -> {
        checkOverdueBooks(); // calls method that checks overdue books
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        dateandtimeLabel = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Library Management System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        btnProfile.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        btnProfile.setText("Profile Info");
        btnProfile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProfile.setIconTextGap(9);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 200, 80));

        jButton3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton3.setText("Return Books");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, 80));

        jButton4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton4.setText("Borrow Books");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 200, 80));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // checks students if they have overdue borrowed books
    private void checkOverdueBooks(){
        
    // connect to database
        try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234")) {
        
        // SQL query to fetch user's record
        String sql = "SELECT BookName, DueDate FROM BorrowedBooks WHERE StudentName = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        
        // set currently logged in user as teh first parameter
        pst.setString(1, SessionManager.userName);

        ResultSet rs = pst.executeQuery();
        
        // string builder to add overdue book info
        StringBuilder overdueBooks = new StringBuilder();
        
        // fetcehes today's date for comparison
        Date today = new Date();
        
        // loop through all the borrowed books returned by the query
        while (rs.next()) {
            // fetch book name and due date
            String bookName = rs.getString("BookName");
            Date dueDate = rs.getDate("DueDate");
            
            // calculate teh difference between tiday and the due date in milliseconds
            long diffMillis = today.getTime() - dueDate.getTime();
            // convert milliseconds to days
            long daysOverdue = TimeUnit.MILLISECONDS.toDays(diffMillis);
            
            // If the book is overdue, add it to the message
            if (daysOverdue > 0) {
                overdueBooks.append(bookName)
                            .append(" - overdue by ")
                            .append(daysOverdue)
                            .append(" day(s)\n");
            }
        }
        
        // If there are overdue books, display a warning dialog
        if (overdueBooks.length() > 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "You have overdue books:\n\n" + overdueBooks.toString(),
                    "Overdue Alert",
                    JOptionPane.WARNING_MESSAGE
            );
        }
        
        // shows error message if database error occurs
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }
    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        this.dispose(); // removes current form
        UserProfileForm UPForm = new UserProfileForm(); // sets LForm variable to store the specified form for redirection
        UPForm.setVisible(true); // makes form visible
    }//GEN-LAST:event_btnProfileActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose(); // removes current form
        ReturnBooks RBForm = new ReturnBooks(); //sets RBForm variable to store the specified form for redirection
        RBForm.setVisible(true); // makes form visible
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose(); // removes current form
        BorrowBooks BBForm = new BorrowBooks(); //sets BBForm variable to store the specified form for redirection
        BBForm.setVisible(true); // makes form visble
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
