/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.regex.*;
/**
 *
 * @author Daeniel Presa
 */
public class UserSignupForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public UserSignupForm() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a"); // fetches date and time with format, placed into fmt 
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt))).start(); // starts timer, every 60k ms = 1 minute, every minute it activates it fetches data and sets it to the label
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt)); // sets the time when program is run
        setLocationRelativeTo(null); // centers the form
        // both makes label have an underline
        employeesignupLabel.setText("<html><u>" + employeesignupLabel.getText() + "</u></html>");
        loginLabel.setText("<html><u>" + loginLabel.getText() + "</u></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        dateandtimeLabel = new javax.swing.JLabel();
        employeesignupLabel = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, 20));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Library Management System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sign Up");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));
        getContentPane().add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 220, -1));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 220, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("ENTER");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 110, -1));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        employeesignupLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        employeesignupLabel.setForeground(new java.awt.Color(204, 255, 255));
        employeesignupLabel.setText("Are you an employee? Click here");
        employeesignupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeesignupLabelMouseClicked(evt);
            }
        });
        getContentPane().add(employeesignupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, 20));
        getContentPane().add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 220, -1));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(204, 255, 255));
        loginLabel.setText("Already have an account? Click here");
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
        });
        getContentPane().add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 20));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String studentID = txtStudentID.getText().trim(); // fetches text field contents
        String studentName = txtStudentName.getText().trim(); // fetches text field contents
        String password = new String(txtPassword.getPassword()); // fetches text field contents

        String regex = "\\d{4}-\\d{7}"; // password pattern for user name (Example: 2025-1234567)

        if (!Pattern.matches(regex, studentID)) { //if pattern doesn't match the user input in text field, send error message
            JOptionPane.showMessageDialog(this, "Student ID must be in format YYYY-1234567", "Invalid ID", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (studentName.isEmpty() || password.isEmpty()) { // if fields are empty, send error message
            JOptionPane.showMessageDialog(this, "Please fill all fields",
                                          "Empty Fields", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // if password contains less than 8 characters, doesn't include an uppercase, lowercase, and a number, send error message
        if (password.length() < 8 ||
            !password.matches(".*[A-Z].*") || 
            !password.matches(".*[a-z].*") ||
            !password.matches(".*\\d.*")){
            JOptionPane.showMessageDialog(this,
                "Password must be at least 8 characters and include:\n" +
                "- 1 uppercase letter\n" +
                "- 1 lowercase letter\n" +
                "- 1 number\n",
                "Invalid Password", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String url = "jdbc:mysql://localhost:3306/lbs"; // stores database url
        String user = "root"; // stores database password
        String pass = "MySQLPW_1234"; // stores database password
        
        // SQL Prompt for inserting Students if all requirements are met, values are blank as default
        String sql = "INSERT INTO Students (StudentID, StudentName, Password) VALUES (?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, pass); // makes a connection with the database
             PreparedStatement pst = conn.prepareStatement(sql)) { // has the sql prompt for values insertion

            pst.setString(1, studentID); // set first value as student id 
            pst.setString(2, studentName); // set second value as student name
            pst.setString(3, password); // set first value as password
            pst.executeUpdate(); // executes prompt
            
            // message dialog for successful signup
            JOptionPane.showMessageDialog(this, "Sign up successful!");
            this.dispose();
            LoginForm LForm = new LoginForm();
            LForm.setVisible(true);

        } catch (SQLException ex) { // catches all errors
            if (ex.getErrorCode() == 1062) { // student already exists, show error message
                JOptionPane.showMessageDialog(this, "Student ID already exists!",
                                              "Error", JOptionPane.ERROR_MESSAGE);
            } else { // if any other database errors may occur, show error message
                JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(),
                                              "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void employeesignupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesignupLabelMouseClicked
        // redirection block
        this.dispose();
        EmployeeSignupForm ESUForm = new EmployeeSignupForm();
        ESUForm.setVisible(true);
    }//GEN-LAST:event_employeesignupLabelMouseClicked

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        // redirection block
        this.dispose();
        LoginForm LForm = new LoginForm();
        LForm.setVisible(true);
    }//GEN-LAST:event_loginLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JLabel employeesignupLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
