package librarymanagementsystem;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;    
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author Daeniel Presa
 */
public class ViewInventory extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    private int selectedBookID = -1;
    private String selectedBookName = null;
    private int selectedAvailableCopies = 0;
    private Object[][] originalBookTableData;

    public ViewInventory() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a");
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt)))
        .start();
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt));
        loadBooks();
        setLocationRelativeTo(null);
        
        btnAddBook.addActionListener(e -> {
            AddBookDialog dialog = new AddBookDialog(this, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        dateandtimeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        btnAddBook = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDeleteRow = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library Management System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        BookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookTable);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 630, 180));

        btnAddBook.setText("Add new book record");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 110, -1));

        btnDeleteRow.setText("Delete Row");
        btnDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRowActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 110, -1));

        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTableMouseClicked
        int row = BookTable.getSelectedRow();
        if (row >= 0) {
        selectedBookID = (int) BookTable.getValueAt(row, 0);
        selectedAvailableCopies = (int) BookTable.getValueAt(row, 2);
        selectedBookName = BookTable.getValueAt(row, 1).toString();
        }
    }//GEN-LAST:event_BookTableMouseClicked
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        EmployeeHomePage EHPForm = new EmployeeHomePage();
        EHPForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (BookTable.isEditing()) {
        BookTable.getCellEditor().stopCellEditing();
    }

    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234")) {

        String updateSQL = "UPDATE BookInventory SET BookName = ?, Author = ?, YearPurchased = ?, AvailableCopies = ? WHERE BookID = ?";
        PreparedStatement pst = con.prepareStatement(updateSQL);

        for (int row = 0; row < BookTable.getRowCount(); row++) {
            int bookID = Integer.parseInt(BookTable.getValueAt(row, 0).toString());
            String bookName = BookTable.getValueAt(row, 1).toString();
            String author = BookTable.getValueAt(row, 2).toString();
            int yearPurchased = Integer.parseInt(BookTable.getValueAt(row, 3).toString());
            int availableCopies = Integer.parseInt(BookTable.getValueAt(row, 4).toString());

            pst.setString(1, bookName);
            pst.setString(2, author);
            pst.setInt(3, yearPurchased);
            pst.setInt(4, availableCopies);
            pst.setInt(5, bookID);

            pst.addBatch();
        }

        pst.executeBatch();

        JOptionPane.showMessageDialog(this, "Updated successfully.");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadBooks();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRowActionPerformed
         int row = BookTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Please select a book to remove.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int bookID = Integer.parseInt(BookTable.getValueAt(row, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this book?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try (Connection con = DriverManager.getConnection(
                 "jdbc:mysql://localhost:3306/lbs",
                 "root",
                 "MySQLPW_1234");
             PreparedStatement ps = con.prepareStatement(
                 "DELETE FROM BookInventory WHERE BookID = ?")) {

            ps.setInt(1, bookID);
            int affectedRows = ps.executeUpdate();

            if (affectedRows > 0) {
                DefaultTableModel model = (DefaultTableModel) BookTable.getModel();
                model.removeRow(row);

                selectedBookID = -1;
                selectedAvailableCopies = 0;
                selectedBookName = null;

                JOptionPane.showMessageDialog(this, "Book deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Book not found in database.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error deleting book: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDeleteRowActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInventory().setVisible(true);
            }
        });
    }
    private void loadBooks() {
        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/lbs",
                "root",
                "MySQLPW_1234")) {

            String sql = "SELECT * FROM BookInventory";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column != 0; // BookID not editable
                }
            };

            model.addColumn("BookID");
            model.addColumn("BookName");
            model.addColumn("Author");
            model.addColumn("YearPurchased");
            model.addColumn("AvailableCopies");

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("BookID"),
                        rs.getString("BookName"),
                        rs.getString("Author"),
                        rs.getInt("YearPurchased"),
                        rs.getInt("AvailableCopies")
                });
            }

            BookTable.setModel(model);
            BookTable.setAutoResizeMode(BookTable.AUTO_RESIZE_OFF);

            originalBookTableData = new Object[BookTable.getRowCount()][BookTable.getColumnCount()];
            for (int i = 0; i < BookTable.getRowCount(); i++) {
                for (int j = 0; j < BookTable.getColumnCount(); j++) {
                originalBookTableData[i][j] = BookTable.getValueAt(i, j);
                }
            }
        
        
            for (int col = 0; col < BookTable.getColumnCount(); col++) {
                int width = 50;
                for (int row = 0; row < BookTable.getRowCount(); row++) {
                    TableCellRenderer renderer = BookTable.getCellRenderer(row, col);
                    Component comp = BookTable.prepareRenderer(renderer, row, col);
                    width = Math.max(comp.getPreferredSize().width + 10, width);
                }

                TableCellRenderer headerRenderer = BookTable.getTableHeader().getDefaultRenderer();
                Component headerComp = headerRenderer.getTableCellRendererComponent(
                        BookTable, 
                        BookTable.getColumnName(col),
                        false, false, 0, col
                );
                width = Math.max(width,headerComp.getPreferredSize().width + 10);
                BookTable.getColumnModel().getColumn(col).setPreferredWidth(width);
            }
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookTable;
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnDeleteRow;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
