package librarymanagementsystem;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;    
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
/**
 *
 * @author Daeniel Presa
 */
public class ViewHistory extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    private int selectedBookID = -1;
    private String selectedBookName = null;
    private int selectedAvailableCopies = 0;
    
    public ViewHistory() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a"); // assigns date and time format
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt))) // timer every minute triggers and updates
        .start();
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt)); // sets current date when running the program
        loadHistory(); // loads table
        setLocationRelativeTo(null); // sets form location to the center
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        dateandtimeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("History:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Library Management System");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(HistoryTable);

        jScrollPane3.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane3);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 500, 140));

        jPanel2.setBackground(new java.awt.Color(87, 87, 87));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // redirection block
        this.dispose();
        EmployeeHomePage EHPForm = new EmployeeHomePage();
        EHPForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHistory().setVisible(true);
            }
        });
    }
    private void loadHistory() {
        // attempt database connection
        try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234")) {
        // SQL query prompt in fetching data
        String sql = "SELECT * FROM TransactionHistory";
        PreparedStatement pst = con.prepareStatement(sql); // stores query in a prepared statement
        ResultSet rs = pst.executeQuery(); // executes query
        
        // creates new model for table
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0; // disables editing
            }
        };
        
        // defines all table columns
        model.addColumn("TransactionID");
        model.addColumn("StudentID");
        model.addColumn("BookName");
        model.addColumn("DateBorrowed");
        model.addColumn("DueDate");
        model.addColumn("ReturnDate");
        model.addColumn("Penalty");
        
        int rowCount = 0;
        // loop thru all rs and add each record to the model
        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getInt("TransactionID"),
                    rs.getString("StudentID"),
                    rs.getString("BookName"),
                    rs.getDate("DateBorrowed"),
                    rs.getDate("DueDate"),
                    rs.getDate("ReturnDate"),
                    rs.getBigDecimal("Penalty")
            });
            rowCount++;
        }
        
        // if no transaction records exists, send message dialog
        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null,
                    "No transaction history records found.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
        // apply model to existing tbale
        HistoryTable.setModel(model);
        HistoryTable.setAutoResizeMode(HistoryTable.AUTO_RESIZE_OFF);
        
        // automatically resizes columns based on content
        if (rowCount > 0) {
            for (int col = 0; col < HistoryTable.getColumnCount(); col++) {
                int maxWidth = 50;

                for (int row = 0; row < HistoryTable.getRowCount(); row++) {
                    TableCellRenderer renderer = HistoryTable.getCellRenderer(row, col);
                    Component comp = HistoryTable.prepareRenderer(renderer, row, col);
                    maxWidth = Math.max(comp.getPreferredSize().width + 10, maxWidth);
                }
                // calculated width based on column headers
                TableCellRenderer headerRenderer = HistoryTable.getTableHeader().getDefaultRenderer();
                Component headerComp = headerRenderer.getTableCellRendererComponent(
                        HistoryTable,
                        HistoryTable.getColumnName(col),
                        false, false, 0, col
                );
                maxWidth = Math.max(maxWidth, headerComp.getPreferredSize().width + 10);
                
                // apply calculated width to column
                HistoryTable.getColumnModel().getColumn(col).setPreferredWidth(maxWidth);
            }
        }
    // error message occurs if any database error occurs
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                null,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HistoryTable;
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
