package librarymanagementsystem;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;    
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author Daeniel Presa
 */
public class ViewUsers extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    private int selectedBookID = -1;
    private String selectedBookName = null;
    private int selectedAvailableCopies = 0;
    
    public ViewUsers() {
        initComponents();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a");
        new Timer(60000, e -> dateandtimeLabel.setText(LocalDateTime.now().format(fmt)))
        .start();
        dateandtimeLabel.setText(LocalDateTime.now().format(fmt));
        loadStudents();
        loadEmployees();
        setLocationRelativeTo(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        dateandtimeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentsTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        dateandtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateandtimeLabel.setText("Date & Time");
        getContentPane().add(dateandtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 10));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Students:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        StudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        StudentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentsTable);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 460, 130));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Library Management System");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel6.setText("Employees:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        EmployeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EmployeeTable);

        jPanel3.add(jScrollPane2);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 460, 130));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentsTableMouseClicked
        int row = StudentsTable.getSelectedRow();
        if (row >= 0) {
        selectedBookID = (int) StudentsTable.getValueAt(row, 0);
        selectedAvailableCopies = (int) StudentsTable.getValueAt(row, 2);
        selectedBookName = StudentsTable.getValueAt(row, 1).toString();
        }
    }//GEN-LAST:event_StudentsTableMouseClicked
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        EmployeeHomePage EHPForm = new EmployeeHomePage();
        EHPForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EmployeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeTableMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsers().setVisible(true);
            }
        });
    }
    private void loadEmployees() {
    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234")) {

        String sql = "SELECT * FROM Employees";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        model.addColumn("EmployeeID");
        model.addColumn("EmployeeName");

        int rowCount = 0;
        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getString("EmployeeID"),
                    rs.getString("EmployeeName"),
            });
            rowCount++;
        }

        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null,
                    "No employee found.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        EmployeeTable.setModel(model);
        EmployeeTable.setAutoResizeMode(EmployeeTable.AUTO_RESIZE_OFF);

        if (rowCount > 0) {
            for (int col = 0; col < EmployeeTable.getColumnCount(); col++) {
                int maxWidth = 50;

                for (int row = 0; row < EmployeeTable.getRowCount(); row++) {
                    TableCellRenderer renderer = EmployeeTable.getCellRenderer(row, col);
                    Component comp = EmployeeTable.prepareRenderer(renderer, row, col);
                    maxWidth = Math.max(comp.getPreferredSize().width + 10, maxWidth);
                }

                TableCellRenderer headerRenderer = EmployeeTable.getTableHeader().getDefaultRenderer();
                Component headerComp = headerRenderer.getTableCellRendererComponent(
                       EmployeeTable,
                        EmployeeTable.getColumnName(col),
                        false, false, 0, col
                );
                maxWidth = Math.max(maxWidth, headerComp.getPreferredSize().width + 10);

                EmployeeTable.getColumnModel().getColumn(col).setPreferredWidth(maxWidth);
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                null,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    private void loadStudents() {
    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/lbs",
            "root",
            "MySQLPW_1234")) {

        String sql = "SELECT * FROM Students";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        model.addColumn("StudentID");
        model.addColumn("StudentName");

        int rowCount = 0;
        while (rs.next()) {
            model.addRow(new Object[]{
                    rs.getString("StudentID"),
                    rs.getString("StudentName"),
            });
            rowCount++;
        }

        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null,
                    "No students found.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        StudentsTable.setModel(model);
        StudentsTable.setAutoResizeMode(StudentsTable.AUTO_RESIZE_OFF);

        if (rowCount > 0) {
            for (int col = 0; col < StudentsTable.getColumnCount(); col++) {
                int maxWidth = 50;

                for (int row = 0; row < StudentsTable.getRowCount(); row++) {
                    TableCellRenderer renderer = StudentsTable.getCellRenderer(row, col);
                    Component comp = StudentsTable.prepareRenderer(renderer, row, col);
                    maxWidth = Math.max(comp.getPreferredSize().width + 10, maxWidth);
                }

                TableCellRenderer headerRenderer = StudentsTable.getTableHeader().getDefaultRenderer();
                Component headerComp = headerRenderer.getTableCellRendererComponent(
                        StudentsTable,
                        StudentsTable.getColumnName(col),
                        false, false, 0, col
                );
                maxWidth = Math.max(maxWidth, headerComp.getPreferredSize().width + 10);

                StudentsTable.getColumnModel().getColumn(col).setPreferredWidth(maxWidth);
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                null,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JTable StudentsTable;
    private javax.swing.JLabel dateandtimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
